name: ci

on:
  push:
    branches:
      - 'master'

env:
  TROCR_VERSION: 0.1.3

jobs:
  Build-and-Push-Container:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ secrets.TROCR_GHCR_USER }}
          password: ${{ secrets.TROCR_GHCR_PASS }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          build-args: TROCR_VERSION=${{ env.TROCR_VERSION }}
          push: true
          tags: ghcr.io/cypx/trocr:latest,ghcr.io/cypx/trocr:${{ env.TROCR_VERSION }}